services:
  - type: web
    name: regio-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_NAME
        value: regio
      - key: DB_PASSWORD
        value: 5854 